### ISSUE TITLE
Build a reduction to pairwise transformer

### ISSUE THREAD

**Issue by istvanp1** [skpref/skpref#18]
Create pairwise comparisons from choices:
Assume we have 4 alternatives: {A, B, C, D}
They have the following covariates unique to them:

Table 1 - features for alternatives:
| alternative | feature 1 | feature 2|
|-------------|-----------|----------|
|A                 | 1            | 2            |
| B                | 3            | 4            |
| C                | 5            | 6            |
| D                | 7            | 8            |

Table 2 -  observations and features that vary by observation.
| offered alternatives | picked alternatives | features 3 |
|---------------------- |----------------------|------------|
| A, B, C                      | B                             | 9              |
| A, B, C, D                  | A, D                        | 10            |

We want to get the following pandas DataFrame in the output with writing:
```python
from skpref.task import ChoiceTask
my_task = ChoiceTask(table2, 'offered alternatives ', 'picked alternatives', secondary_table=table1, secondary_key= 'alternative')
parwise_df = my_task.subset_vec.pairwise_reducer(style="positive")
display(parwise_df)
```
| observation | top | boot |
|--------------|------|------|
| 0 | A | B |
| 0 | A | C |
| 1 | B | A |
| 1 | B | D |
| 1 | C | A |
| 1 | C | D |

```python
from skpref.task import ChoiceTask
my_task = ChoiceTask(table2, 'offered alternatives ', 'picked alternatives', secondary_table=table1, secondary_key= 'alternative')
parwise_df = my_task.subset_vec.pairwise_reducer(style="reciprocal")
display(parwise_df)
```
| observation | alt1 | alt2 | alt1_top|
|--------------|------|-----|----------|
| 0 | A | B | 1 |
| 0 | B | A | 0 |
| 0 | A | C | 1 |
| 0 | C | A | 0 |
| 1 | B | A | 1 |
| 1 | A | B | 0 |
| 1 | B | D | 1 |
| 1 | D | B | 0 |
| 1 | C | A | 1 |
| 1 | A | C | 0 |
| 1 | C | D | 1 |
| 1 | D | C | 0 |

```python
from skpref.task import ChoiceTask
my_task = ChoiceTask(table2, 'offered alternatives ', 'picked alternatives', secondary_table=table1, secondary_key= 'alternative')
parwise_df = my_task.subset_vec.pairwise_reducer(style="reciprocal", rejection=-1)
display(parwise_df)
```
| observation | alt1 | alt2 | alt1_top|
|--------------|------|-----|----------|
| 0 | A | B | 1 |
| 0 | B | A | -1 |
| 0 | A | C | 1 |
| 0 | C | A | -1 |
| 1 | B | A | 1 |
| 1 | A | B | -1 |
| 1 | B | D | 1 |
| 1 | D | B | -1 |
| 1 | C | A | 1 |
| 1 | A | C | -1 |
| 1 | C | D | 1 |
| 1 | D | C | -1 |

Once this output exsits the developer can decide how to merge on features from table 1 and table 2 for the model in question.

steps:
- [x] Get response variables numpy array
- [x] Create function that allows pandas DataFrame to be created from this.
- [x] Write unit tests

**Comment by istvanp1** [comment]
@prithagupta can you confirm this is right?

**Comment by prithagupta** [comment]
@istvanp1 I have some questions regarding your example, why does **Table 3** have a new feature called **feature 3**, Plus why are you creating different numpy arrays for each feature of each alternative ??

**Comment by istvanp1** [comment]
So Table 1 is a table that contains all the alternatives and features that vary on the alternative level: this can be the budget of  team, the flavour of each product etc... features 1 and 2 in this case
Table 2 contains the comparisons and the choices but also features that vary on the comparison level: the weather during the match, the music that was playing during the choice etc... feature 3 in this case.
These two tables are the information that the users have.
The rest describes how to create the reduction of a choice to a pairwise comparison. So we create the numpy array of the comparisons in a [winner, loser], [loser, winner] format then for each first element in the comparison we have the features that vary on the element level [feature 1, feature 2] then we have the feature that varies on the comparison level [feature 3].
I'm guessing the numpy arrays of [feature 1, feature 2] will be subtracted in the SVM case. Not sure how or if SVM deals with features like feature 3.

**Comment by prithagupta** [comment]
The setting you are talking about is Dyadic Predictions, where **feature 3** could be renamed as **context-feature 1** because this feature defines the environment in which the decision was taken. Another question I have is, the number of **context-features** is fixed for one data set or choice scenario? Like in the above case it is one.

Pairwise Comparison Dataset: Assume that for context **c**, and alternative **x** and **y**. features If **x>y** or x is chosen:
for SVM would look like:
(c,x-y). or (c,x-y). But unfortunately, I cannot find a paper for it. It's just a general practice I have seen.
A paper which actually deals with Dyad Ranking by reducing it to pairwise preference relations is:
https://www.researchgate.net/profile/Dirk_Schaefer6/publication/308112416_Plackett-Luce_Networks_for_Dyad_Ranking/links/57da59ca08ae5292a373cd4b.pdf

**Comment by istvanp1** [comment]
Thanks for the material. I guess the only things I need confirmation at the moment are the following: For the reduction to pairwise models, do we do comparisons both ways i.e. A gets picked from [A,B] gets represented both in terms of [A,B] = 1 and [B,A] = 0. If yes do we represent failure as 0 or -1 for SVM?

**Comment by prithagupta** [comment]
That question is about the consistency of the representation of the positive and the negative classes in the created pairwise (classification) data:
- **Case 1**: Classification data has points with 1 (positive) and 0 (negative).
- **Case 2**: Classification data has points with 1 (positive) and -1 (negative).

**Comment by istvanp1** [comment]
OK, I've enabled all the functionality that have been mentioned in a pairwise reducer function in the SubsetPosetVec object. This can help us convert the input data in the right format. Please let me know if this works for the SVM case.
