### ISSUE TITLE
Create a hierarchy for reduction techniques in the interface

### ISSUE THREAD

**Issue by istvanp1** [skpref/skpref#31]
The observations of ranking and choice models can be represented in a hierarchy of how the result can be transformed.
* It is possible to transform any fully ranked result into a choice (or poset) by defining a cut-off say top 5 is chosen. Once this data is generated it is possible to run a choice model on this. It is also possible to transform any fully ranked model into pairwise comparisons and then run pairwise comparison models on them.
* It is also possible to transform any choice result into pairwise comparisons, but it is not possible to directly transform a choice into a full ordered rank without doing any modelling.

This creates a hierarchy system like the one in this image

![modelling_flow_choice_models](https://user-images.githubusercontent.com/25740842/78501174-70b2a180-7752-11ea-87a7-bd6c7cb5d7c3.jpeg)

Going down the hierarchy from the original observed data to use techniques that are lower to then predict the results in the original observed level, for example, creating pairwise comparisons from ranking data, running a pairwise model and then using the global ranking of the pairwise model to make ranking predictions is called a reduction technique.

We also refer to reduction technique when the modelling is represented as a classical classifier. For example, defining with 1/0 whether an object gets chosen and then running logistic regression on this treating each choice as independent.

Currently, the Bradley Terry module can detect when this is happening an it can apply the reduction technique when a ChoiceTask is fed into the fit_task method.

* [ ] We need to create a hierarchical structure than can detect the level of the hierarchy coming into the modelling techniques and decide whether a reduction technique is needed or not.
* [ ] We need to make sure that the ultimate reduction to classifier is also enabled.

**Comment by fkiraly** [comment]
To add the example we discussed:
a reduction compositor `RedRankingToPairwiseDummy` could wrap a pairwise comparison learner and make a ranking learner, by breaking up observed rankings into pairs, and predicting using the learnt ranking.

For example, `RedRankingToPairwiseDummy(BradleyTerry(myparams), myparams)` would construct a ranking learner from BT pairwise.

One side aspect to consider is that there may be, of course, different ways to reduce A to B and these may be different first-order learners.

**Comment by fkiraly** [comment]
@istvanp1 , I think the first post (which you sneakily added by an edit), together with discussion in #34 and #36, highlights some interesting points:
* what are the tasks, and what are common reduction techniques between them? What are these exactly, algorithmically? We should have a list, and add these to #29. Might take some time to spell it out (but you have time for your thesis...)
* how to deal with multiple different options for reduction between the same tasks? I think they should be compositors.
* "default" reduction vs non-default reduction. Some reduction techniques might be very standard, so a suggested default as in #36 makes a lot of sense to me, e.g., via mixin. But how should the interface behave if we want to apply a different one, e.g., via compositor? Is that a simple override in the wrapper?
* you also raise a very interesting point via your differently coloured arrows: some models internally produce a representation which could be used for a "higher complexity task", but are fitted at lower level - e.g., vanilla Bradley-Terry which is fitted to a pairwise comparison data set but infers a total ranking. A reduction technique could use a pairwise comparison model for choice modelling or ranking, by converting each choice into multiple pairs for fitting, infer a total ranking, and use this for choice or ranking in the predict mode.
My take-away for this is that we should think carefully about dedicated interface points for inference/insection, e.g., to get the inferred ranking within the reduction wrapper described above.

**Comment by istvanp1** [comment]
if we have the fit_task() style architecture, do we need to also have reduction wrappers for models inside skpref?
* Tasks by definition know which type they are, i.e. a ChoiceTask by definition knows that it's a choice
* pairwise comparison models e.g. BradleyTerry() know that they are pairwise comparison strategies by definition.
* the purpose of fit_task() is so that the user can enter a task inside a method of a pairwise comparison and it's function is to prepare the data for the fit() and predict() methods of the model. So these work effectively as the reduction wrappers when a higher level task is entered.
* We only really need reduction wrappers in the case when a user wants to use a scikit-learn model for a choice task, since these don't have fit_task() methods. But outside of this I'm not convinced that a ReductionWrapper() is needed as well as the fit_task() architecture.

**Comment by istvanp1** [comment]
Default vs. non default
Some of the reducers in the package can cater for some of the formats we can foresee. For example right now the pairwise_reducer() in a SubsetPosetVector() takes some arguments that determine whether rejections should be 0 or -1 (the latter being applied in SVM), but also if the outputs should be one sample or reciprocal i.e. if we want each choice to figure once in a chosen / rejected setting or to feature twice as a chosen / rejected , rejected / chosen setting, which can be a technique to increase the observations.
For different ways of reduction at the moment we would need someone to develop them or fork the code and develop for themselves and maybe merge back in if it is not too specific a singular use case.

**Comment by istvanp1** [comment]
The last point would echo the previous point I made, except with predict_task() i.e. the user would know that they're using for example, BradleyTerry() to predict a more complex task, and the hopeful assumption is that they know the limitations that this method has 

> if we have the fit_task() style architecture, do we need to also have reduction wrappers for models inside skpref?
> 
> * Tasks by definition know which type they are, i.e. a ChoiceTask by definition knows that it's a choice
> * pairwise comparison models e.g. BradleyTerry() know that they are pairwise comparison strategies by definition.
> * the purpose of fit_task() is so that the user can enter a task inside a method of a pairwise comparison and it's function is to prepare the data for the fit() and predict() methods of the model. So these work effectively as the reduction wrappers when a higher level task is entered.
> * We only really need reduction wrappers in the case when a user wants to use a scikit-learn model for a choice task, since these don't have fit_task() methods. But outside of this I'm not convinced that a ReductionWrapper() is needed as well as the fit_task() architecture.

**Comment by fkiraly** [comment]
>We only really need reduction wrappers in the case when a user wants to use a scikit-learn model for a choice task, since these don't have fit_task() methods. But outside of this I'm not convinced that a ReductionWrapper() is needed as well as the fit_task() architecture.

Disagreed, there are multiple options to reduce between choice/ranking tasks as well!

Though agree with the idea that there should be some "default" reductions which are inbuilt, these are sugar for common use cases.

**Comment by istvanp1** [comment]
What I meant was that we only need an explicit class for reduction when using scikit-learn models. When using skpref models the fit_task() should be able to deal with all the reductions highlighted in the chart. So there will be reduction between choice / ranking but not explicitly this will always happen in fit_task().
