### ISSUE TITLE
Design a new Task called Pairwise task

### ISSUE THREAD

**Issue by istvanp1** [skpref/skpref#34]
Currently pairwise tasks (for example team 1 playing against team2) are captured by ChoiceTask. However the likely data representations for Pairwise choice and subset choice are quite different.
Pairwise data is likely to look like this:
![image](https://user-images.githubusercontent.com/25740842/78687087-b191ee00-78eb-11ea-9a3e-132f7cdf6772.png)
Where there is a column for option 1, a column for option 2 and a flag that relates 1/0 whether one of the columns are chosen. In this case we need the user to tell us what are the names of the columns that contain the two different alternatives, what is the column that contains the 1/0 flag and finally which of the columns winning does a 1 correspond to.
Currently with ChoiceTask the specifications for this model are as follows:
```python
NBA_results_task_train = ChoiceTask(primary_table=train_data,
                                    primary_table_alternatives_names=['team1', 'team2'],
                                    primary_table_target_name ='team1_wins',
                                    target_column_correspondence='team1')
```

Another likely data representation for subset choice (one from many or many from many) is as follows:
![image](https://user-images.githubusercontent.com/25740842/78687441-12212b00-78ec-11ea-9355-82a8c2e1919e.png)
Where there is a column in which each row contains a list of alternatives and another column in which each row contains a subset of the alternatives column. Note that there is no 1/0 column whether one has chosen or not. Here we need the user to tell us which column contains the alternatives and which one the subsets and looks quite different.
```python
products_bought_train = ChoiceTask(primary_table=train_data,
                                    primary_table_alternatives_names='alternatives',
                                    primary_table_target_name ='choice')

```
Having two different ways of specifying a ChoiceTask can get confusing for end users and for developers since there then need to be checks on which format the data is in (at the moment BradleyTerry checks if target_column_correspondence is None to go one way about the data or another).

This would get less confusing if create a PairwiseTask which deals only with data of the first format and keep ChoiceTask to only deal with data in the second format. Both would be powered by the same SubsetPosetVector but making this distinction more explicit can make usage and development easier.

Franz, we know that a PairwiseTask was originally not considered since conceptually it's mathematically an easy subcase of a ChoiceTask, but the data representation of these two cases is probably different enough to warrant the development of the PairwiseTask anyway. Let me know if you have any comments.

**Comment by fkiraly** [comment]
I can see the argument, and am tentatively in favour.

One question though: you can also encode choice-ouf-of-4 in this way, e.g., with columns player1, player2, player3, player4 playing, say, the card game Tichu - the winner column being one of the numbers 1,2,3,4.

What is the argument for singling out choice-out-of-2 in the interface?

**Comment by istvanp1** [comment]
Hmmm that is right. The best excuse that I can come up with for creating a PairwiseTask in the light of that is that the use case of having team1 vs. team2 (or player1 vs. player2) is expected to be very common. So it makes sense for us to go out of our way to make these models work nicely on the already pairwise set up.
For datasets in the format you mentioned we put a little extra work on the user end to convert it into the format of a set of alternatives and chosen subset of alternatives column like the product example.
But this might just be my personal biased experience so happy to be told otherwise!

**Comment by fkiraly** [comment]
Perhaps that is indeed the argument - the use case is much more frequent?
Makes sense to me.

In either case it might be useful to think about a utility function or a transformer that does the wrapping/unwrapping, even if it is not an explicit task spec.

**Comment by istvanp1** [comment]
PairwiseComparisonTask() created and pulled into master.
