### ISSUE TITLE
Improve modeling architecture to allow several models to be built

### ISSUE THREAD

**Issue by istvanp1** [skpref/skpref#36]
Proposed new modeling architecture:
```python
from sklearn import BaseEstimator
Model(ABC):
    task_unpacker()
    fit()
    predict()
    fit_task():
        fit(task_unpacker())
    predict_task()

PairwiseModel(Model):
    task_unpacker():
        """If Task is PairwiseTask() then don't transform the data
        otherwise transform data into pairwise data
        Merges tables together as necessary with the several data sources, 
        based on what tasks specify (i.e. features, secondary table etc...)
        """
    task_prediction_packer(predictions, choice_cut_off=1):
        """ If Task is not PairwiseTask() then aggregates the predictions up to the level
        of the task.
        """
    predict()
    predict_proba()
    predict_choice()

    predict_task():
       predictions = predict()
       task_prediction_packer(predictions)

    predict_proba_task():
        predictions = predict_proba()
        task_prediction_packer(predictions)

    predict_choice_task():
       predictions = predict_choice()
       task_prediction_packer(predictions)

GLMPairwiseModel(PairwiseModel):
    task_unpacker():
        """Passes the right reducer parameters through the PairwiseModel task_unpacker"""

SVMPairwiseModel(PairwiseModel):
    task_unpacker():
        """Passes variables through the PairwiseModel task_unpacker s.t. inferior preferences
        are represented by 0."""

BradleyTerry(GLMPairwiseModel, BaseEstimator):
    fit()
    predict()
    predict_proba()
    predict_choice()

SVM(SVMPairwiseModel, BaseEstimator):
     fit()
    predict()
    predict_choice()
```

**Comment by istvanp1** [comment]
dependent on issue number #34

**Comment by fkiraly** [comment]
Makes sense on high level to me.

Questions:
* is it assumed that models only cater for one task type? How does this fit together with only having one `predict` method in model?
* should `task_unpacker` be private?
* architeturally, `task_unpacker` could be in a model type specific mixin rather than in a model class specific ancestor (e.g., `SVMPairwiseModel`), if it is applying to, say, all pairwise models rather than just all SVMs, if it's always a certain default reduction. Or is there something specific about SVM, GLM etc that you anticipate happening in unpacking?

**Comment by fkiraly** [comment]
From call: should probably record that `task_unpacker` calls conversion/accessor functionality of the data container passed to it, i.e., does not directly manipulate data but asks the data container to do this.
The job of `task_unpacker` is to reshape the data as inputs for `fit` or predict` which should have easy-to-use, easy-to-format arguments (i.e., not data containers but arrays or such).

**Comment by istvanp1** [comment]
Yes, and additionally to clarify that each task has a specific data container, and each of these data containers will know how to convert the data down to a specific format as per the hierarchy in issue #31 also pasted here:
![image](https://user-images.githubusercontent.com/25740842/79848009-6b8f5c80-83b8-11ea-93ac-b688730c65cf.png)

**Comment by istvanp1** [comment]
Progress update: architecture has been redesigned and pushed, available for viewing in branch correspondent to this issue name.
Next steps: build function that pack tasks to predict from a pairwise comparison to a choice.

**Comment by istvanp1** [comment]
## predict_task_unpacker()
### The objective
In the case when the data is not the same family of tasks as the modelling family that is being used to predict it, for example super market shopping basket data (choice task) being modeled by Bradley Terry (Pairwise Comparison model), we need a function that translates the choice data into pairwise comparisons.
Currently we will cover the cases of converting from a choice task to a pairwise task, but in the future we will also need to develop a rank task to pairwise task.

Example choice data for training:
|choice|alternatives|
|-------|-------------|
|[A, B]  | [A, B, C, D] | 

Example pairwise comparison data for training:
|option A|Option B| Option A chosen |
|-------|-------------|---------------|
|A | C | 1 |
|D|A| 0 |
|B|C| 1|
B|D| 1 |

Example choice data for prediction:
|alternatives|
|-------------|
| [A, B, C, D] | 

Example pairwise comparison data for prediction:
|option A|Option B| 
|-------|-------------|
|A | B |
|A|C|
|A|D|
|B|C|
|B|D|
|C|D|

### Plan for the solution
For train_task_unpacker() this was done in such a way that every chosen object was a winner against every not chosen object, and not chosen objects were not compared to each other and winning objects were also not compared to each other. The case when predicting is different because all we know is the list of alternatives, so everything needs be compared against everything.

### Proposed unit tests
Enter a choice task and see if everything compared to everything comes out in the entry for the predict() function of the pairwise model.

## predict_task_packer()
### The objective:
It should be a function that for all tasks scales the results up to the right level. For example if a choice problem is modeled as a pairwise comparison in a fit_task() then the predict_task() should return choices, even though the predict() function of the model will be outputting pairwise predictions. When going from pairwise to choice, which is the only case the architecture can currently handle it is not clear how to select the number of objects chosen.

Example pairwise comparison data with prediction:
|option A|Option B| Prediction for option A chosen | Observation | number of choices|
|-------|-------------|-----------| --------------|----------------------|
|A | B | 0.58|0|2|
|A|C| 0.516|0|2|
|A|D| 0.468|0|2|
|B|C| 0.645|0|2|
|B|D| 0.1|0|2|
|C|D| 0.16|0|2|

Example return from predict_task(some_choice_task):
np.array([A, D])

more questions with no answers from my side at the moment:
* How does predict_task() work in going from pairwise to choice?
* How does predict_task_proba() work?
    * Do we predict the probability of every possible combination of given number of choices for a choise?
    * How do we compute the probability such that P({A,B} | {A, B, C}) = 1-P({C}|{A,B,C})

### Plan for the solution
For ease of implementation, allow the user to enter an array of number of chosen objects, for each observation in case they have previously modeled this. (We can also develop further these methods by doing our own internal way of predicting number of chosen objects, and check how this is dealt with in the literature @prithagupta mentioned some statistical tests that they use for determining this). This array will default to an array of a constant where the constant is the rounded mean of the chosen number of alternatives in the training set. This parameter will need to come from the predict_task, since that's the only public method that is connected here.

### Proposed unit tests
Check if entering different arrays will achieve different number of alternatives chosen at each level.
