### ISSUE TITLE
GridSearchCV compatibility or homologue for parameter tuning

### ISSUE THREAD

**Issue by fkiraly** [skpref/skpref#46]
I remember your prototype version had a working integration with `sklearn` `GridSearchCV`.

Looks like this no longer exists? 
Would suggest to move/fix that as a reasonably high priority, especially since it used to work.

**Comment by istvanp1** [comment]
This exists, you can see it at the end of the notebook [here](https://github.com/skpref/skpref/blob/master/skpref/examples/example_using_choice_data.ipynb) and [here](https://github.com/skpref/skpref/blob/master/skpref/examples/example_using_sports_data.ipynb).

Closing issue, please reopen it or open another one if the implementation should improve.

**Comment by fkiraly** [comment]
Indeed it does. Seem to have missed it. Sorry.
